package com.sofaacademy.sofaminiproject.utils.helpers

import android.content.Context
import android.content.res.Resources
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import com.sofaacademy.sofaminiproject.R
import java.text.Normalizer
import java.util.Locale

/**
 * Uzeto is sofaScore projekta :D
 */
object FlagHelper {

    val flags = initFlagsMap()

    @JvmStatic
    fun getFlagBitmap(context: Context, fileName: String?): Bitmap? {
        val tmpFileName = fileName.transformFileName()
        var flagBitmap: Bitmap? = null

        try {
            flagBitmap = decodeBitmapAndCacheFlag(context, tmpFileName)
        } catch (e1: Resources.NotFoundException) {
            // there is no flag for selected file, use default flag
            try {
                flagBitmap = decodeBitmapAndCacheFlag(context, "sofascore_logomark")
            } catch (e: Resources.NotFoundException) {
                e.printStackTrace()
            }
        }
        return flagBitmap
    }

    @JvmStatic
    fun getFlagResource(fileName: String?): Int {
        return flags[fileName.transformFileName()] ?: R.drawable.sofascore_logomark
    }

    fun String?.transformFileName(): String {
        var tmpFileName = this?.setForSystemFolders() ?: "sofascore_logomark"

        tmpFileName = when (tmpFileName) {
            "itf_men", "itf_women" -> "itf"
            "challenger_women" -> "wta"
            "grand_slam" -> "trophy_color"
            "in_progress" -> "calendar_color"
            else -> tmpFileName
        }

        return tmpFileName
    }

    private fun decodeBitmapAndCacheFlag(context: Context, fileName: String): Bitmap? {
        val resId = getFlagResource(fileName)
        val inputStream = context.resources.openRawResource(resId)
        return BitmapFactory.decodeStream(inputStream)
    }

    private fun String.setForSystemFolders(): String {
        return this.lowercase(Locale.getDefault())
            .removeSpecialCharacters()
            .replace(".", "")
            .split("(-)|( )".toRegex())
            .joinToString(separator = "_")
            .trim()
    }

    private fun String.removeSpecialCharacters(): String {
        return Normalizer.normalize(this, Normalizer.Form.NFD)
            .replace("[^\\p{ASCII}]".toRegex(), "")
    }

    private fun initFlagsMap(): HashMap<String, Int> {
        val flagsMap = HashMap<String, Int>()
        flagsMap.apply {
            // Countries
            put("afghanistan", R.drawable.afghanistan)
            put("albania", R.drawable.albania)
            put("algeria", R.drawable.algeria)
            put("american_samoa", R.drawable.american_samoa)
            put("andorra", R.drawable.andorra)
            put("angola", R.drawable.angola)
            put("anguilla", R.drawable.anguilla)
            put("antigua_and_barbuda", R.drawable.antigua_and_barbuda)
            put("argentina", R.drawable.argentina)
            put("armenia", R.drawable.armenia)
            put("aruba", R.drawable.aruba)
            put("australia", R.drawable.australia)
            put("austria", R.drawable.austria)
            put("azerbaijan", R.drawable.azerbaijan)
            put("bahamas", R.drawable.bahamas)
            put("bahrain", R.drawable.bahrain)
            put("bangladesh", R.drawable.bangladesh)
            put("barbados", R.drawable.barbados)
            put("belarus", R.drawable.belarus)
            put("belgium", R.drawable.belgium)
            put("belize", R.drawable.belize)
            put("benin", R.drawable.benin)
            put("bermuda", R.drawable.bermuda)
            put("bhutan", R.drawable.bhutan)
            put("bolivia", R.drawable.bolivia)
            put("bosnia_herzegovina", R.drawable.bosnia_herzegovina)
            put("botswana", R.drawable.botswana)
            put("brazil", R.drawable.brazil)
            put("british_virgin_islands", R.drawable.british_virgin_islands)
            put("brunei", R.drawable.brunei)
            put("bulgaria", R.drawable.bulgaria)
            put("burkina_faso", R.drawable.burkina_faso)
            put("burundi", R.drawable.burundi)
            put("cambodia", R.drawable.cambodia)
            put("cameroon", R.drawable.cameroon)
            put("canada", R.drawable.canada)
            put("cape_verde", R.drawable.cape_verde)
            put("cayman_islands", R.drawable.cayman_islands)
            put("central_african_rep", R.drawable.central_african_rep)
            put("chad", R.drawable.chad)
            put("chile", R.drawable.chile)
            put("china", R.drawable.china)
            put("colombia", R.drawable.colombia)
            put("comoros", R.drawable.comoros)
            put("congo", R.drawable.congo)
            put("cook_islands", R.drawable.cook_islands)
            put("costa_rica", R.drawable.costa_rica)
            put("ivory_coast", R.drawable.ivory_coast)
            put("croatia", R.drawable.croatia)
            put("cuba", R.drawable.cuba)
            put("curacao", R.drawable.curacao)
            put("cyprus", R.drawable.cyprus)
            put("czech_republic", R.drawable.czech_republic)
            put("dr_congo", R.drawable.dr_congo)
            put("denmark", R.drawable.denmark)
            put("djibouti", R.drawable.djibouti)
            put("dominica", R.drawable.dominica)
            put("dominican_rep", R.drawable.dominican_rep)
            put("timor_leste", R.drawable.timor_leste)
            put("ecuador", R.drawable.ecuador)
            put("egypt", R.drawable.egypt)
            put("el_salvador", R.drawable.el_salvador)
            put("equatorial_guinea", R.drawable.equatorial_guinea)
            put("eritrea", R.drawable.eritrea)
            put("estonia", R.drawable.estonia)
            put("ethiopia", R.drawable.ethiopia)
            put("falkland_islands", R.drawable.falkland_islands)
            put("faroe_islands", R.drawable.faroe_islands)
            put("fiji", R.drawable.fiji)
            put("finland", R.drawable.finland)
            put("france", R.drawable.france)
            put("french_guyana", R.drawable.french_guyana)
            put("tahiti", R.drawable.tahiti)
            put("gabon", R.drawable.gabon)
            put("gambia", R.drawable.gambia)
            put("georgia", R.drawable.georgia)
            put("germany", R.drawable.germany)
            put("ghana", R.drawable.ghana)
            put("gibraltar", R.drawable.gibraltar)
            put("greece", R.drawable.greece)
            put("greenland", R.drawable.greenland)
            put("grenada", R.drawable.grenada)
            put("guam", R.drawable.guam)
            put("guatemala", R.drawable.guatemala)
            put("guinea", R.drawable.guinea)
            put("guinea_bissau", R.drawable.guinea_bissau)
            put("guyana", R.drawable.guyana)
            put("haiti", R.drawable.haiti)
            put("honduras", R.drawable.honduras)
            put("hong_kong", R.drawable.hong_kong)
            put("hungary", R.drawable.hungary)
            put("iceland", R.drawable.iceland)
            put("india", R.drawable.india)
            put("indonesia", R.drawable.indonesia)
            put("iran", R.drawable.iran)
            put("iraq", R.drawable.iraq)
            put("israel", R.drawable.israel)
            put("ireland", R.drawable.ireland)
            put("italy", R.drawable.italy)
            put("jamaica", R.drawable.jamaica)
            put("japan", R.drawable.japan)
            put("jordan", R.drawable.jordan)
            put("kazakhstan", R.drawable.kazakhstan)
            put("kenya", R.drawable.kenya)
            put("kiribati", R.drawable.kiribati)
            put("north_korea", R.drawable.north_korea)
            put("south_korea", R.drawable.south_korea)
            put("kosovo", R.drawable.kosovo)
            put("kuwait", R.drawable.kuwait)
            put("kyrgyzstan", R.drawable.kyrgyzstan)
            put("laos", R.drawable.laos)
            put("latvia", R.drawable.latvia)
            put("lebanon", R.drawable.lebanon)
            put("lesotho", R.drawable.lesotho)
            put("liberia", R.drawable.liberia)
            put("libya", R.drawable.libya)
            put("liechtenstein", R.drawable.liechtenstein)
            put("lithuania", R.drawable.lithuania)
            put("luxembourg", R.drawable.luxembourg)
            put("macao", R.drawable.macao)
            put("macedonia", R.drawable.macedonia)
            put("madagascar", R.drawable.madagascar)
            put("malawi", R.drawable.malawi)
            put("malaysia", R.drawable.malaysia)
            put("maldives", R.drawable.maldives)
            put("mali", R.drawable.mali)
            put("malta", R.drawable.malta)
            put("marshall_islands", R.drawable.marshall_islands)
            put("mauritania", R.drawable.mauritania)
            put("mauritius", R.drawable.mauritius)
            put("mayotte", R.drawable.mayotte)
            put("mexico", R.drawable.mexico)
            put("micronesia", R.drawable.micronesia)
            put("moldova", R.drawable.moldova)
            put("monaco", R.drawable.monaco)
            put("mongolia", R.drawable.mongolia)
            put("montenegro", R.drawable.montenegro)
            put("montserrat", R.drawable.montserrat)
            put("morocco", R.drawable.morocco)
            put("mozambique", R.drawable.mozambique)
            put("burma", R.drawable.burma)
            put("namibia", R.drawable.namibia)
            put("nauru", R.drawable.nauru)
            put("nepal", R.drawable.nepal)
            put("netherlands", R.drawable.netherlands)
            put("new_caledonia", R.drawable.new_caledonia)
            put("new_zealand", R.drawable.new_zealand)
            put("nicaragua", R.drawable.nicaragua)
            put("niger", R.drawable.niger)
            put("nigeria", R.drawable.nigeria)
            put("niue", R.drawable.niue)
            put("northern_mariana_islands", R.drawable.northern_mariana_islands)
            put("norway", R.drawable.norway)
            put("oman", R.drawable.oman)
            put("pakistan", R.drawable.pakistan)
            put("palau", R.drawable.palau)
            put("panama", R.drawable.panama)
            put("papua_new_guinea", R.drawable.papua_new_guinea)
            put("paraguay", R.drawable.paraguay)
            put("peru", R.drawable.peru)
            put("philippines", R.drawable.philippines)
            put("poland", R.drawable.poland)
            put("portugal", R.drawable.portugal)
            put("puerto_rico", R.drawable.puerto_rico)
            put("qatar", R.drawable.qatar)
            put("france", R.drawable.france)
            put("romania", R.drawable.romania)
            put("russia", R.drawable.russia)
            put("rwanda", R.drawable.rwanda)
            put("st_kitts_and_nevis", R.drawable.st_kitts_and_nevis)
            put("saint_lucia", R.drawable.saint_lucia)
            put("saint_pierre_and_miquelon", R.drawable.saint_pierre_and_miquelon)
            put("saint_vincent_and_the_grenadines", R.drawable.saint_vincent_and_the_grenadines)
            put("samoa", R.drawable.samoa)
            put("san_marino", R.drawable.san_marino)
            put("sao_tome_and_principe", R.drawable.sao_tome_and_principe)
            put("saudi_arabia", R.drawable.saudi_arabia)
            put("senegal", R.drawable.senegal)
            put("serbia", R.drawable.serbia)
            put("seychelles", R.drawable.seychelles)
            put("sierra_leone", R.drawable.sierra_leone)
            put("singapore", R.drawable.singapore)
            put("slovakia", R.drawable.slovakia)
            put("slovenia", R.drawable.slovenia)
            put("solomon_islands", R.drawable.solomon_islands)
            put("somalia", R.drawable.somalia)
            put("south_africa", R.drawable.south_africa)
            put("spain", R.drawable.spain)
            put("sri_lanka", R.drawable.sri_lanka)
            put("sudan", R.drawable.sudan)
            put("surinam", R.drawable.surinam)
            put("swaziland", R.drawable.swaziland)
            put("eswatini", R.drawable.swaziland)
            put("sweden", R.drawable.sweden)
            put("switzerland", R.drawable.switzerland)
            put("syria", R.drawable.syria)
            put("taiwan", R.drawable.taiwan)
            put("tajikistan", R.drawable.tajikistan)
            put("tanzania", R.drawable.tanzania)
            put("thailand", R.drawable.thailand)
            put("togo", R.drawable.togo)
            put("tonga", R.drawable.tonga)
            put("trinidad_and_tobago", R.drawable.trinidad_and_tobago)
            put("tunisia", R.drawable.tunisia)
            put("turkey", R.drawable.turkey)
            put("turkiye", R.drawable.turkiye)
            put("turkmenistan", R.drawable.turkmenistan)
            put("turks_and_caicos_islands", R.drawable.turks_and_caicos_islands)
            put("uganda", R.drawable.uganda)
            put("ukraine", R.drawable.ukraine)
            put("united_arab_emirates", R.drawable.uae)
            put("great_britain", R.drawable.great_britain)
            put("usa", R.drawable.usa)
            put("virgin_islands", R.drawable.virgin_islands)
            put("uruguay", R.drawable.uruguay)
            put("uzbekistan", R.drawable.uzbekistan)
            put("vanuatu", R.drawable.vanuatu)
            put("vatican", R.drawable.vatican)
            put("venezuela", R.drawable.venezuela)
            put("vietnam", R.drawable.vietnam)
            put("wallis_and_futuna", R.drawable.wallis_and_futuna)
            put("yemen", R.drawable.yemen)
            put("zambia", R.drawable.zambia)
            put("zimbabwe", R.drawable.zimbabwe)
            put("south_sudan", R.drawable.south_sudan)
            put("tuvalu", R.drawable.tuvalu)
            put("palestine", R.drawable.palestine)
            put("guadeloupe", R.drawable.guadeloupe)
            put("martinique", R.drawable.martinique)
            put("england", R.drawable.england)
            put("scotland", R.drawable.scotland)
            put("wales", R.drawable.wales)
            put("northern_ireland", R.drawable.n_ireland)
            // Other
            put("atp", R.drawable.atp)
            put("antarctica", R.drawable.antarctica)
            put("arabic", R.drawable.arabic)
            put("asia", R.drawable.asia)
            put("bikes", R.drawable.bikes)
            put("billie_jean_king_cup", R.drawable.billie_jean_king_cup)
            put("bonaire", R.drawable.bonaire)
            put("bouvet_island", R.drawable.bouvet_island)
            put("british_indian_ocean_territory", R.drawable.british_indian_ocean_territory)
            put("calendar_color", R.drawable.calendar_color)
            put("catalonia", R.drawable.catalonia)
            put("challenger", R.drawable.challenger)
            put("christmas_island", R.drawable.christmas_island)
            put("cayman_islands", R.drawable.cayman_islands)
            put("cocos_keeling_islands", R.drawable.cocos_keeling_islands)
            put("csgo", R.drawable.csgo)
            put("curacao", R.drawable.curacao)
            put("davis_cup", R.drawable.davis_cup)
            put("copa_america_color", R.drawable.copa_america_color)
            put("ctl", R.drawable.ctl)
            put("dota_2", R.drawable.dota_2)
            put("dtm", R.drawable.dtm)
            put("east_timor", R.drawable.east_timor)
            put("ecuatorial_guinea", R.drawable.ecuatorial_guinea)
            put("electronic_leagues", R.drawable.electronic_leagues)
            put("esoccer", R.drawable.esoccer)
            put("euro2016_color", R.drawable.euro2016_color)
            put("europe", R.drawable.europe)
            put("falkland_islands_malvinas", R.drawable.falkland_islands_malvinas)
            put("federation_cup", R.drawable.federation_cup)
            put("exhibition", R.drawable.exhibition)
            put("fifa", R.drawable.fifa)
            put("sofascore_logomark", R.drawable.sofascore_logomark)
            put("former_east_timor", R.drawable.former_east_timor)
            put("formula_1", R.drawable.formula_1)
            put("formula_e", R.drawable.formula_e)
            put("french_southern_territories", R.drawable.french_southern_territories)
            put("granada", R.drawable.granada)
            put("guernsey", R.drawable.guernsey)
            put("heard_island_and_mcdonald_islands", R.drawable.heard_island_and_mcdonald_islands)
            put("holy_see_vatican_city_state", R.drawable.holy_see_vatican_city_state)
            put("hopman_cup", R.drawable.hopman_cup)
            put("indycar", R.drawable.indycar)
            put("international", R.drawable.international)
            put("iptl", R.drawable.iptl)
            put("itf", R.drawable.itf)
            put("isle_of_man", R.drawable.isle_of_man)
            put("jersey", R.drawable.jersey)
            put("lol", R.drawable.lol)
            put("moto2", R.drawable.moto2)
            put("moto3", R.drawable.moto3)
            put("motogp", R.drawable.motogp)
            put("nascar", R.drawable.nascar)
            put("nauru", R.drawable.nauru)
            put("netherlands_antilles", R.drawable.netherlands_antilles)
            put("north_and_central_america", R.drawable.north_and_central_america)
            put("not_cancelled", R.drawable.not_cancelled)
            put("oceania", R.drawable.oceania)
            put("pitcairn", R.drawable.pitcairn)
            put("player_transfer", R.drawable.player_transfer)
            put("rally", R.drawable.rally)
            put("rugby_league", R.drawable.rugby_league)
            put("rugby_union", R.drawable.rugby_union)
            put("rugby_union_sevens", R.drawable.rugby_union_sevens)
            put("simulated_reality_league", R.drawable.simulated_reality_league)
            put(
                "south_georgia_and_the_south_sandwich_islands",
                R.drawable.south_georgia_and_the_south_sandwich_islands
            )
            put("superbike", R.drawable.superbike)
            put("svalbard_and_jan_mayen", R.drawable.svalbard_and_jan_mayen)
            put("tokelau", R.drawable.tokelau)
            put("trophy_color", R.drawable.trophy_color)
            put("uefa", R.drawable.uefa)
            put("union_sevens", R.drawable.union_sevens)
            put("west_indies", R.drawable.west_indies)
            put("wta", R.drawable.wta)
            put("zaire", R.drawable.zaire)
            put("zanzibar", R.drawable.zanzibar)
            put("africa", R.drawable.africa)
            put("aland_islands", R.drawable.aland_islands)
            put("american_virgin_island", R.drawable.american_virgin_island)
            put("andalusia", R.drawable.andalusia)
            put("basque", R.drawable.basque)
            put("myanmar", R.drawable.myanmar)
            put("norfolk_island", R.drawable.norfolk_island)
            put("north_america", R.drawable.north_america)
            put("south_america", R.drawable.south_america)
            put("saint_martin", R.drawable.saint_martin)
            put("sint_maarten", R.drawable.sint_maarten)
        }
        return flagsMap
    }
}
